In [40]:
import pandas as pd
print('Libraries imported successfully!!!')

Libraries imported successfully!!!

In [41]:
#Loading of Data
df=pd.read_csv('patient_records.csv')
print('Number of Rows and columns :',df.shape)

Number of Rows and columns : (500, 7)

In [42]:
#information related to Data
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               500 non-null    object
 1   Age                      500 non-null    int64
 2   Biomarker_Level          480 non-null    float64
 3   Pre_Existing_Conditions  500 non-null    int64
 4   Vaccine_Dose_mcg         500 non-null    float64
 5   Prior_Reaction_History   192 non-null    object
 6   Reaction_Score           500 non-null    int64
dtypes: float64(2), int64(3), object(2)
memory usage: 27.5+ KB

,Age,Biomarker_Level,Pre_Existing_Conditions,Vaccine_Dose_mcg,Reaction_Score
count,500.000000,480.000000,500.000000,500.000000,500.000000
mean,51.444000,5.283438,1.262000,86.552400,0.490000
std,19.444976,2.841475,1.195078,36.232862,0.500401
min,18.000000,0.640000,0.000000,25.100000,0.000000
25%,35.000000,3.175000,0.000000,56.775000,0.000000
50%,51.000000,4.820000,1.000000,84.550000,0.000000
75%,68.250000,6.952500,2.000000,118.675000,1.000000
max,85.000000,15.760000,4.000000,150.000000,1.000000

In [43]:
#checking for duplicated data
print('duplicted data :',df.duplicated().sum())

duplicted data : 0

In [44]:
#checking of missing values 
print('Missing values:\n',df.isnull().sum())

Missing values:
 Patient_ID                   0
Age                          0
Biomarker_Level             20
Pre_Existing_Conditions      0
Vaccine_Dose_mcg             0
Prior_Reaction_History     308
Reaction_Score               0
dtype: int64

In [45]:
#removing the patient id column as it does not effect the result
df=df.drop('Patient_ID',axis=1)

In [46]:
#Handling missing values
df['Biomarker_Level']=df['Biomarker_Level'].fillna(5.28)
df.isnull().sum()
df['Prior_Reaction_History']=df['Prior_Reaction_History'].fillna('None')
print('Missing values successully resolved!!!')

Missing values successully resolved!!!

In [47]:
df.head(15)

,Age,Biomarker_Level,Pre_Existing_Conditions,Vaccine_Dose_mcg,Prior_Reaction_History,Reaction_Score
0,24,4.53,1,83.5,Mild,1
1,70,1.65,1,46.2,None,0
2,62,1.92,1,124.6,None,1
3,47,12.48,1,57.6,None,1
4,47,2.11,1,44.2,Mild,0
5,76,5.88,3,55.8,None,1
6,23,2.44,3,130.3,None,0
7,65,7.47,1,66.3,Mild,0
8,31,3.78,0,110.8,Mild,0
9,24,1.79,1,132.1,None,0
10,53,4.06,1,34.7,None,0
11,84,3.35,1,120.6,Moderate,0
12,68,8.43,2,63.5,None,1
13,69,5.91,1,52.1,Mild,0
14,66,4.80,0,111.1,None,0

In [48]:
#encoding or mapping the Prior_Reaction_History column
df['Prior_Reaction_History']=df['Prior_Reaction_History'].map({
    'None':0,
    'Mild':1,
    'Moderate':2
})

In [49]:
df.head(15)

,Age,Biomarker_Level,Pre_Existing_Conditions,Vaccine_Dose_mcg,Prior_Reaction_History,Reaction_Score
0,24,4.53,1,83.5,1,1
1,70,1.65,1,46.2,0,0
2,62,1.92,1,124.6,0,1
3,47,12.48,1,57.6,0,1
4,47,2.11,1,44.2,1,0
5,76,5.88,3,55.8,0,1
6,23,2.44,3,130.3,0,0
7,65,7.47,1,66.3,1,0
8,31,3.78,0,110.8,1,0
9,24,1.79,1,132.1,0,0
10,53,4.06,1,34.7,0,0
11,84,3.35,1,120.6,2,0
12,68,8.43,2,63.5,0,1
13,69,5.91,1,52.1,1,0
14,66,4.80,0,111.1,0,0

In [50]:
df.to_csv(r"D:\COMPUTER SCIENCE\PRIME BATCH\PROJECTS\6.Vaccine safety & Dosage\data\patient_records_cleaned.csv")
print('data saved successfully!!!')

data saved successfully!!!

In [51]:
df.columns

Index(['Age', 'Biomarker_Level', 'Pre_Existing_Conditions', 'Vaccine_Dose_mcg',
       'Prior_Reaction_History', 'Reaction_Score'],
      dtype='object')

In [55]:
df['Reaction_Score'].value_counts()

Reaction_Score
0    255
1    245
Name: count, dtype: int64